scsi: ufs: fix compilation errors with gcc5
When compiling with gcc5, it throws below errors:

* drivers/scsi/ufs/ufs-qcom.c: In function 'ufs_qcom_hce_enable_notify':
* drivers/scsi/ufs/ufs-qcom.c:352:10: warning: switch condition has boolean
* value [-Wswitch-bool] error, forbidden warning: ufs-qcom.c:352

This is because we are using the boolean value in switch condition and it
seems to be forbidden by compiler (by default). Fix this by using the
proper enum type instead of boolean.

Signed-off-by: Subhash Jadavani <subhashj@codeaurora.org>
[venkatg@codeaurora.org: resolved trivial merge conflict]
Signed-off-by: Venkat Gopalakrishnan <venkatg@codeaurora.org>
Change-Id: Ie4e15143f5e01d95c499f4e7c674743c35524071